on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]

name: CodeSee Map

jobs:
  test_map_action:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Run CodeSee Map Analysis
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      # codesee-detect-languages has an output with id languages.
      - name: Detect Languages
        id: detect-languages
        uses: Codesee-io/codesee-detect-languages-action@177c4c765fc8d128984b3cb7f7d8df8fdbcec21d

      - name: Configure JDK 16
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9
        if: ${{ fromJSON(steps.detect-languages.outputs.languages).java }}
        with:
          java-version: '16'
          distribution: 'zulu'

      # CodeSee Maps Go support uses a static binary so there's no setup step required.

      - name: Configure Node.js 14
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8
        if: ${{ fromJSON(steps.detect-languages.outputs.languages).javascript }}
        with:
          node-version: '14'

      - name: Configure Python 3.x
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e
        if: ${{ fromJSON(steps.detect-languages.outputs.languages).python }}
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configure Ruby '3.x'
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f
        if: ${{ fromJSON(steps.detect-languages.outputs.languages).ruby }}
        with:
          ruby-version: '3.0'

      # CodeSee Maps Rust support uses a static binary so there's no setup step required.

      - name: Generate Map
        id: generate-map
        uses: Codesee-io/codesee-map-action@938f7135ad2978103c7519e4e2c45d8a2b392442
        with:
          step: map
          github_ref: ${{ github.ref }}
          languages: ${{ steps.detect-languages.outputs.languages }}

      - name: Upload Map
        id: upload-map
        uses: Codesee-io/codesee-map-action@938f7135ad2978103c7519e4e2c45d8a2b392442
        with:
          step: mapUpload
          api_token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
          github_ref: ${{ github.ref }}
      
      - name: Insights
        id: insights
        uses: Codesee-io/codesee-map-action@938f7135ad2978103c7519e4e2c45d8a2b392442
        with:
          step: insights
          api_token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
          github_ref: ${{ github.ref }}
